### ISSUE TITLE
Multiple bots in 1 process login recovery

### ISSUE THREAD

**Issue by rannmann** [antal-k/csgoempire-deposit-bot#28]
On startup, if a bot runs into an HTTP 502 from Steam, which isn't uncommon during high load (and due to CS2 it seems to be all the time now), it never tries to reconnect.  If the config is set to single bot, it's no problem to start the process again, but when running 2 accounts in the same process it seems to be that 1 will connect and 1 will fail, then you kill the process, try again, and the other one will fail and the failing one will succeed.

If there's a 502 error from Steam, it should retry the login automatically in a minute.

Example of account 1 succeeding and 2 failing:
![image](https://user-images.githubusercontent.com/1002752/227730950-64716b51-2e75-4f08-936a-1c201a6a9b9a.png)

Then retrying and account 1 failing and 2 succeeding:
![image](https://user-images.githubusercontent.com/1002752/227730975-c5560b7f-3e89-4c20-9c48-9291ce9442fb.png)

**Comment by rannmann** [comment]
Additionally, in rare instance the bot will startup with a proper exception:

```js
Error: HTTP error 502
    at SteamCommunity._checkHttpError (/media/flexin_storage/web/csgoempire-deposit-bot/node_modules/steamcommunity/components/http.js:108:9)
    at Request._callback (/media/flexin_storage/web/csgoempire-deposit-bot/node_modules/steamcommunity/components/http.js:50:61)
    at Request.self.callback (/media/flexin_storage/web/csgoempire-deposit-bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/media/flexin_storage/web/csgoempire-deposit-bot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/media/flexin_storage/web/csgoempire-deposit-bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12) {
  code: 502
}
```
